name: Build and Deploy React Frontend to Cloudfront
on: 
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs: 
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read 
    env:
      AWS_S3_BUCKET: www.domingocarvajalads.me
      DIST: build
      REGION: us-east-1
      DISTRIBUTION_ID: E2H58HKZ9PYWAX
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::253163167097:role/S3-PIPELINE-FRONTEND
        aws-region: us-east-1

    - name: Install Dependencies
      run: |
        cd react-aws
        npm install --save-dev cross-env
        npm install

    - name: Build React Application
      run: |
        cd react-aws
        npm run build

    - name: Copy Files to S3 Bucket
      run: |
        cd react-aws
        aws s3 sync ${{ env.DIST }} s3://${{ env.AWS_S3_BUCKET }} --delete
    
    - name: Update Cloudfront Distribution
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ env.DISTRIBUTION_ID }} --paths "/*"