---
name: Build and Deploy React Frontend to Cloudfront
on: 
  push:
    branches:
      - main
jobs: 
  build-and-deploy:
  runs-on: ubuntu-latest
  env:
    AWS_S3_BUCKET: www.domingocarvajalads.me
    DIST: /aws-react/build
    REGION: us-east-1
    DISTRIBUTION_ID: E2H58HKZ9PYWAX
  steps:
  - name: Checkout Repository
    uses: actions/checkout@v2

  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-access-key-id: AKIATV4NTLV4TC6KK75Y
      aws-secret-access-key: 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
      aws-region: ${{ env.REGION }}

  - name: Install Dependencies
    run: |
      cd react-aws
      npm install

  - name: Build React Application
    run: |
      cd react-aws
      npm run build

  - name: Copy Files to S3 Bucket
    run: |
      aws s3 sync ${{ env.DIST }} s3://${{ env.AWS_S3_BUCKET }} --delete
  
  - name: Update Cloudfront Distribution
    run: |
      aws cloudfront create-invalidation --distribution-id ${{ env.DISTRIBUTION_ID }} --paths "/*"