name: React Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        cd react-aws
        npm install --save-dev cross-env
        npm install

    - name: Build React Application
      run: |
        cd react-aws
        npm run build

    # - name: Run Unit Tests
    #   run: |
    #     cd react-aws/src
    #     npm test

    - name: Ejecutar pruebas
      run: npm test

    - name: Linting del código
      run: npm run lint

    - name: TruffleHog Enterprise scan
      uses: trufflesecurity/TruffleHog-Enterprise-Github-Action@main
      with:
          args: --fail-verified ${{ github.event.repository.default_branch }} HEAD




