name: React Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14 

    - name: Change Working Directory
      run: cd Sample-01
        
    - name: Install Dependencies
      run: npm install

    - name: Run Unit Tests
      run: npm test

    # - name: Check Code Formatting with Prettier
    #   run: npm run prettier -- --check

    - name: TruffleHog Enterprise scan
      uses: trufflesecurity/TruffleHog-Enterprise-Github-Action@main
      with:
          args: --fail-verified ${{ github.event.repository.default_branch }} HEAD




