name: React Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        cd react-aws
        npm install --save-dev cross-env
        npm install

    - name: Build React Application
      run: |
        cd react-aws
        npm run build

    - name: Ejecutar pruebas
      run: |
        cd react-aws
        npm test -- --testPathPattern=src/views/__tests__/Home.test.js

    - name: TruffleHog Enterprise scan
      uses: trufflesecurity/TruffleHog-Enterprise-Github-Action@main
      with:
          args: --fail-verified ${{ github.event.repository.default_branch }} HEAD




